<div class="nav-pf-vertical nav-pf-vertical-with-sub-menus nav-pf-persistent-secondary">
    <ul class="list-group">
        <li class="list-group-item mobile-nav-item-pf visible-xs-block <?php echo $sellActive ?? ''; ?>">
            <a href="/panel/sell">
                <span class="fa fa-dashboard" data-toggle="tooltip" title="" data-original-title="SELL"></span>
                <span class="list-group-item-value">SELL</span>
            </a>
        </li>
        <li class="list-group-item mobile-nav-item-pf visible-xs-block <?php echo $buyActive ?? ''; ?>">
            <a href="/panel/buy">
                <span class="fa fa-dashboard" data-toggle="tooltip" title="" data-original-title="BUY"></span>
                <span class="list-group-item-value">BUY</span>
            </a>
        </li>
        <li class="list-group-item <?php echo $buyDashboardActive ?? '' ?>">
            <a href="/panel/buy/dashboard">
                <span class="fa fa-dashboard" data-toggle="tooltip" title="" data-original-title="Dashboard"></span>
                <span class="list-group-item-value">Dashboard</span>
            </a>
        </li>


        <li class="list-group-item secondary-nav-item-pf mobile-nav-item-pf visible-xs-block">
            <a href="#0">
                <span class="pficon pficon-user" data-toggle="tooltip" title="" data-original-title="User"></span>
                <span class="list-group-item-value dropdown-title">User</span>
            </a>
            <div id="user-secondary" class="nav-pf-secondary-nav">
                <div class="nav-item-pf-header">
                    <a href="#0" class="secondary-collapse-toggle-pf" data-toggle="collapse-secondary-nav"></a>
                    <span>User</span>
                </div>

                <ul class="list-group">
                    <li class="list-group-item">
                        <a href="/panel/logout">
                            <span class="list-group-item-value">Logout</span>
                        </a>
                    </li>
                </ul>
            </div>
        </li>

    </ul>

</div>