<div class="nav-pf-vertical nav-pf-vertical-with-sub-menus nav-pf-persistent-secondary">
    <ul class="list-group">
        <li class="list-group-item mobile-nav-item-pf visible-xs-block <?php echo $sellActive ?? ''; ?>">
            <a href="/panel/sell">
                <span class="fa fa-dashboard" data-toggle="tooltip" title="" data-original-title="SELL"></span>
                <span class="list-group-item-value">SELL</span>
            </a>
        </li>
        <li class="list-group-item mobile-nav-item-pf visible-xs-block <?php echo $buyActive ?? ''; ?>">
            <a href="/panel/buy">
                <span class="fa fa-dashboard" data-toggle="tooltip" title="" data-original-title="BUY"></span>
                <span class="list-group-item-value">BUY</span>
            </a>
        </li>
        <li class="list-group-item <?php echo $sellDashboardActive ?? '' ?>">
            <a href="/panel/sell/dashboard">
                <span class="fa fa-dashboard" data-toggle="tooltip" title="" data-original-title="Dashboard"></span>
                <span class="list-group-item-value">Dashboard</span>
            </a>
        </li>
        <li class="list-group-item <?php echo $addSrvActive ?? ''; ?>">
            <a href="/panel/server/add">
                <span class="fa fa-server" data-toggle="tooltip" title="" data-original-title="Add a Server"></span>
                <span class="list-group-item-value">Add a Server</span>
            </a>
        </li>
        <li class="list-group-item secondary-nav-item-pf <?php echo $srvActive ?? ''; ?>" data-target="#ipsum-secondary">
            <a href="/panel/server/status">
                <span class="fa fa-space-shuttle" data-toggle="tooltip" title="" data-original-title="Ipsum"></span>
                <span class="list-group-item-value">Your Servers</span>
            </a>

            <div id="-secondary" class="nav-pf-secondary-nav">
                <div class="nav-item-pf-header">
                    <a href="/panel/server/status" class="secondary-collapse-toggle-pf" data-toggle="collapse-secondary-nav"></a>
                    <span>Your Servers</span>
                </div>
                <ul class="list-group">
                    <li class="list-group-item <?php echo $statusActive ?? ''; ?>" data-target="#ipsum-intellegam-tertiary">
                        <a href="/panel/server/status">
                            <span class="list-group-item-value">Status</span>
                        </a>

                    </li>
                    <li class="list-group-item <?php echo $logsActive ?? ''; ?>" data-target="#ipsum-copiosae-tertiary">
                        <a href="/panel/server/logs">
                            <span class="list-group-item-value">Logs</span>
                        </a>

                    </li>
                    <li class="list-group-item <?php echo $metricsActive ?? ''; ?>" data-target="#ipsum-patrioque-tertiary">
                        <a href="/panel/server/metrics">
                            <span class="list-group-item-value">Metrics</span>
                        </a>
                    </li>
                </ul>
            </div>


        </li>

        <li class="list-group-item secondary-nav-item-pf mobile-nav-item-pf visible-xs-block">
            <a href="#0">
                <span class="pficon pficon-user" data-toggle="tooltip" title="" data-original-title="User"></span>
                <span class="list-group-item-value dropdown-title">User</span>
            </a>
            <div id="user-secondary" class="nav-pf-secondary-nav">
                <div class="nav-item-pf-header">
                    <a href="#0" class="secondary-collapse-toggle-pf" data-toggle="collapse-secondary-nav"></a>
                    <span>User</span>
                </div>

                <ul class="list-group">
                    <li class="list-group-item">
                        <a href="/panel/logout">
                            <span class="list-group-item-value">Logout</span>
                        </a>
                    </li>
                </ul>
            </div>
        </li>

    </ul>

</div>