<?php /** @var \Helio\Panel\Model\User $user */ ?>
<div class="modal fade" id="addJob" tabindex="-1" role="dialog"
     aria-labelledby="Add a new Job" aria-hidden="true"
     data-id-name="jobid" data-endpoint="job"
     data-container-selector="#helio-joblist"
     data-container-endpoint="user/joblist"
>
    <div class="modal-dialog modal-lg wizard-pf">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close wizard-pf-dismiss" data-dismiss="modal" aria-hidden="true"
                        aria-label="Close">
                    <span class="pficon pficon-close"></span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Add a new Job</h4>
            </div>
            <div class="modal-body">

                <div class="wizard-pf-steps hidden">
                    <ul class="wizard-pf-steps-indicator wizard-pf-steps-alt-indicator active">

                        <li class="wizard-pf-step active">
                            <a href="#"><span class="wizard-pf-step-number">1</span><span class="wizard-pf-step-title">Job Settings</span>
                                <span class="wizard-pf-step-title-substep active">Description</span>
                                <span class="wizard-pf-step-title-substep">Settings</span>
                            </a>
                        </li>

                        <li class="wizard-pf-step disabled">
                            <a href="#">
                                <span class="wizard-pf-step-number">2</span>
                                <span class="wizard-pf-step-title">Application</span>
                                <span class="wizard-pf-step-title-substep">Type</span>
                                <span class="wizard-pf-step-title-substep">Deployment</span>
                            </a>
                        </li>

                        <li class="wizard-pf-step disabled">
                            <a href="#">
                                <span class="wizard-pf-step-number">3</span>
                                <span class="wizard-pf-step-title">Review</span>
                                <span class="wizard-pf-step-title-substep">Summary</span>
                                <span class="wizard-pf-step-title-substep">Progress</span>
                            </a>
                        </li>
                    </ul>

                    <ul class="wizard-pf-steps-alt">
                        <li class="wizard-pf-step-alt active">
                            <a href="#">
                                <span class="wizard-pf-step-alt-number">1</span>
                                <span class="wizard-pf-step-alt-title">Job Settings</span>
                            </a>
                            <ul>
                                <li class="wizard-pf-step-alt-substep active"><a href="">1A. Description</a></li>
                                <li class="wizard-pf-step-alt-substep disabled"><a href="#">1B. Settings</a></li>
                            </ul>
                        </li>

                        <li class="wizard-pf-step-alt">
                            <a href="#">
                                <span class="wizard-pf-step-alt-number">2</span>
                                <span class="wizard-pf-step-alt-title">Application</span>
                            </a>
                            <ul class="hidden">
                                <li class="wizard-pf-step-alt-substep disabled"><a href="#">2A. Type</a></li>
                                <li class="wizard-pf-step-alt-substep disabled"><a href="#">2B. Deployment</a></li>
                            </ul>
                        </li>

                        <li class="wizard-pf-step-alt">
                            <a href="#">
                                <span class="wizard-pf-step-alt-number">3</span>
                                <span class="wizard-pf-step-alt-title">Review</span>
                            </a>
                            <ul class="hidden">
                                <li class="wizard-pf-step-alt-substep disabled"><a href="#">3A. Summary</a></li>
                                <li class="wizard-pf-step-alt-substep disabled wizard-pf-progress-link"><a href="#">3B.
                                        Progress</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>

                <div class="wizard-pf-row">
                    <div class="wizard-pf-sidebar hidden">
                        <ul class="list-group">
                            <li class="list-group-item active">
                                <a href="#">
                                    <span class="wizard-pf-substep-number">1A.</span>
                                    <span class="wizard-pf-substep-title">Description</span>
                                </a>
                            </li>
                            <li class="list-group-item disabled">
                                <a href="#">
                                    <span class="wizard-pf-substep-number">1B.</span>
                                    <span class="wizard-pf-substep-title">Settings</span>
                                </a>
                            </li>
                        </ul>
                        <ul class="list-group hidden">
                            <li class="list-group-item disabled">
                                <a href="#">
                                    <span class="wizard-pf-substep-number">2A.</span>
                                    <span class="wizard-pf-substep-title">Type</span>
                                </a>
                            </li>
                            <li class="list-group-item disabled">
                                <a href="#">
                                    <span class="wizard-pf-substep-number">2B.</span>
                                    <span class="wizard-pf-substep-title">Deployment</span>
                                </a>
                            </li>
                        </ul>
                        <ul class="list-group hidden">
                            <li class="list-group-item disabled">
                                <a>
                                    <span class="wizard-pf-substep-number">3A.</span>
                                    <span class="wizard-pf-substep-title">Summary</span>
                                </a>
                            </li>
                            <li class="list-group-item disabled wizard-pf-progress-link">
                                <a>
                                    <span class="wizard-pf-substep-number">3B.</span>
                                    <span class="wizard-pf-substep-title">Progress</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="wizard-pf-main">
                        <div class="wizard-pf-loading blank-slate-pf">
                            <div class="spinner spinner-lg blank-slate-pf-icon"></div>
                            <h3 class="blank-slate-pf-main-action">Loading...</h3>
                            <p class="blank-slate-pf-secondary-action">Loading should not take long.</p>
                        </div>
                        <div class="wizard-pf-contents hidden">
                            <form class="form-horizontal">
                                <div class="form-group required">
                                    <label class="col-sm-2 control-label required-pf" for="jobname">Job Name</label>
                                    <div class="col-sm-10">
                                        <input id="jobname" name="jobname" type="text" class="form-control" required/>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="wizard-pf-contents hidden">
                            <form class="form-horizontal">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label required-pf" for="jobtype">Type</label>
                                    <div class="col-sm-10">
                                        <select class="selectpicker form-control" name="jobtype" id="jobtype"
                                                required>
                                            <option value="">Select Application...</option>
                                            <option value="gitlab">Gitlab CI Runner</option>
                                            <option value="ep85">EnergyPlus 8.5 Runner</option>
                                            <option value="busybox">Busybox demo</option>
                                            <option value="docker">Docker Exec</option>
                                            <option value="matlab" disabled>Matlab Cloud Application</option>
                                            <option value="energyplus" disabled>EnergyPlus</option>
                                            <option value="bitbucket" disabled>Bitbucket CI Runner</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group option-value-gitlab hidden">
                                    <label class="col-sm-2 control-label required-pf" for="gitlabEndpoint">
                                        Gitlab API URL
                                    </label>
                                    <div class="col-sm-10">
                                        <input type="text" name="gitlabEndpoint" id="gitlabEndpoint"
                                               class="form-control" required>
                                    </div>
                                </div>
                                <div class="form-group option-value-gitlab hidden">
                                    <label class="col-sm-2 control-label" for="gitlabToken">
                                        Gitlab Token
                                    </label>
                                    <div class="col-sm-10">
                                        <input type="text" name="gitlabToken" id="gitlabToken"
                                               class="form-control">
                                    </div>
                                </div>
                                <div class="form-group option-value-gitlab hidden">
                                    <label class="col-sm-2 control-label" for="gitlabTags">
                                        Gitlab Tags
                                    </label>
                                    <div class="col-sm-10">
                                        <input type="text" name="gitlabTags" id="gitlabTags"
                                               class="form-control"
                                               value="<?php echo $user->getConfig('gitlabtags'); ?>"
                                        >
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="wizard-pf-contents hidden">
                            <form class="form-horizontal">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label" for="cpus">
                                        # CPUs
                                    </label>
                                    <div class="col-sm-10">
                                        <input type="text" name="cpus" id="cpus">
                                    </div>
                                    <label class="col-sm-2 control-label" for="gpus">
                                        # GPUs
                                    </label>
                                    <div class="col-sm-10">
                                        <input type="text" name="gpus" id="gpus">
                                    </div>
                                    <label class="col-sm-2 control-label" for="location">
                                        Location / Juristiction
                                    </label>
                                    <div class="col-sm-10">
                                        <input type="text" name="location" id="location">
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="wizard-pf-contents hidden">
                            <form class="form-horizontal">
                                <div class="form-group required">
                                    <label class="col-sm-2 control-label required-pf" for="billingReference">
                                        Billing Reference
                                    </label>
                                    <div class="col-sm-10">
                                        <input type="text" name="billingReference" id="billingReference"
                                               class="form-control" required>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label" for="budget">
                                        Maximal total Budget for this execution
                                    </label>
                                    <div class="col-sm-10">
                                        <input type="text" name="budget" id="budget"
                                               class="form-control">
                                    </div>
                                </div>
                                <div class="form-group required">
                                    <label class="col-sm-2 control-label required-pf" for="free">
                                        Is this an OpenSource or NGO Workload?
                                    </label>
                                    <div class="col-sm-10">
                                        <input value="on" type="checkbox" name="free" id="free"
                                               class="switch">
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="wizard-pf-contents hidden">
                            <div class="wizard-pf-review-steps">
                                Validation successful. You can create your instance now, please submit below.
                            </div>
                        </div>
                        <div class="wizard-pf-contents hidden">
                            <div class="wizard-pf-process blank-slate-pf">
                                <div class="spinner spinner-lg blank-slate-pf-icon"></div>
                                <h3 class="blank-slate-pf-main-action">Service is being provisioned. This might take a few minutes.</h3>
                                <p class="blank-slate-pf-secondary-action">
                                    &nbsp;
                                </p>
                            </div>
                            <div class="wizard-pf-complete blank-slate-pf hidden">
                                <div class="wizard-pf-success-icon"><span class="glyphicon glyphicon-ok-circle"></span>
                                </div>
                                <h3 class="blank-slate-pf-main-action">Job successfully saved</h3>
                                <p class="blank-slate-pf-secondary-action">
                                    The job is now registered and can be executed.<br/>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer wizard-pf-footer">
                <button type="submit" class="btn btn-primary wizard-pf-next disabled" disabled="disabled">
          <span class="wizard-pf-button-text">
            Next
          </span>
                    <span class="i fa fa-angle-right"></span>
                </button>
                <button type="button" class="btn btn-default wizard-pf-back disabled" disabled="disabled">
                    <span class="i fa fa-angle-left"></span>
                    <span class="wizard-pf-button-text">
            Back
          </span>
                </button>
                <button type="button" class="btn btn-default btn-cancel wizard-pf-cancel wizard-pf-dismiss">Cancel
                </button>
                <button type="button" class="btn btn-primary hidden wizard-pf-close wizard-pf-dismiss">Close</button>
            </div><!-- /.wizard-pf-footer -->

        </div>
    </div>
</div>