<div class="col-md-12">

    <h2>Login / Register</h2>

    <div class="col-md-6" id="register">
        <form id="register" action="/user/login" method="POST">
            <div class="form-group input-group-lg">
                <label for="email">What is your Email address?</label>
                <input name="email" class="form-control" id="email" type="email" placeholder="Email" required/>
                <small id="emailHelp" class="form-text text-muted">Please use an Address that you have always access to,
                    since we currently only support password-less login via magic link.
                    We'll never share your email with anyone else.
                </small>
            </div>
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
    <div class="">
        <p>
        Alternatively, execute the following script from your server:
        <pre>
        curl -X POST -H "Content-Type: application/json" -d '{"fqdn":"your.host.name","email":"xyz@example.com"}' https://panel.idling.host/server/create
        </pre>
        </p>
    </div>
</div>