<section class="hero">
    <div class="hero__inner wrapper">
        <div class="hero__content">
            <h1 class="display">
                Monetize your unused space
            </h1>
            <p class="text text--big">
                Have some servers running under capacity?<br>
                Utilize idling computing capacity.
            </p>
        </div>
    </div>
</section>
<section class="values">

    <div class="conversion conversion--box">
        <div class="conversion__inner">
            <div class="conversion__title">
                <h2 class="display">
                    Login<br/>
                    <span class="c--white">To the future.</span>
                </h2>
            </div>
            <div class="newsletter">
                <div class="newsletter__inner">
                    <form id="register" action="/user/login" method="POST">
                        <label for="email" class="small">What is your Email address?</label>
                        <input name="email" class="newsletter__input" id="email" type="email" placeholder="Email"
                               required/>

                        <br/>
                    </form>
                </div>
                <button type="submit" class="button button--dark">Login / Register</button>
            </div>

            <break></break>
            <div><br/>
                <small class="small">
                    Please use an email address that you have always access to,
                    since we currently only support password-less login via magic link.
                </small>
                <br/>
                <strong class="c--white">
                    We'll never share your email address with anyone.
                </strong>
                <br/><br/>
                Alternatively, execute the following script from your server:
                <pre>
curl -fsSL un.idling.host -o start-computing.sh
if shasum -a 1 -s -c <(echo '321120a4347749dc9348b0db4039fec327dff651  start-computing.sh'); then
    ./start-computing.sh
fi</pre>
            </div>
        </div>
    </div>
</section>
