<!DOCTYPE html>
<html class="helio <?php echo $htmlClass ?? 'layout-pf layout-pf-fixed transitions' ?>" lang="en">
<?php include '_head.phtml' ?>
<body class="<?php echo $bodyClass ?? 'cards-pf' ?>">
<div class="toast-notifications-list-pf"></div>
<?php
if (isset($childTemplate)) {
    /** @noinspection PhpIncludeInspection */
    include $childTemplate . '.phtml';
} else {
    echo 'Error: no template set.';
}

include '_footer.phtml'

?>

</body>
</html>
