# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/php:7.2-fpm-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-

      - run: composer install -n -q -o

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: composer run test

      # remove dev packages
      - run: composer install -o -n -q --prefer-dist --no-dev

      - run:
          name: deploy to prod
          command: |
            mkdir ~/.ssh || rm -f ~/.ssh/known_hosts
            mv ./.circleci/known_hosts ~/.ssh/
            rsync -rptgoDzL --delete src cnf vendor www cli-config.php composer.* panelproto@nbf01.opsserver.ch:.
            ssh panelproto@nbf01.opsserver.ch "source .zshrc; vendor/bin/doctrine orm:schema-tool:update --force"
            ssh panelproto@nbf01.opsserver.ch "sudo /usr/sbin/service php72-fpm reload"
            ssh panelproto@nbf01.opsserver.ch "sudo /usr/sbin/service php72-fpm reload"