<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        <?php
        if (isset($title)) {
            echo htmlspecialchars($title);
        } else {
            echo 'Helio';
        }
        ?>
    </title>

    <link rel="stylesheet" href="/pf/patternfly/dist/css/patternfly.min.css">
    <link rel="stylesheet" href="/pf/patternfly/dist/css/patternfly-additions.min.css">

    <link rel="stylesheet" type="text/css" href="/style.css">

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>