<?php /** @var \Helio\Panel\Model\User $user */ ?>
<div class="container-fluid">
    <div>
        <h2>
            Impersonate
        </h2>
        <ul>
            <?php
            if (isset($users)) {
                /** @var \Helio\Panel\Model\User $u */
                foreach ($users as $u) {
                    if ($u->getId() !== $user->getId()) {
                        echo '<button class="btn btn-primary impersonate" data-userid="' . $u->getId() . '">'.$u->getEmail().'</button>';
                    }
                }
            }
            ?>
        </ul>
    </div>
    <div id="helio-joblist" class="list-group list-view-pf list-view-pf-view loadable">
        <div class="list-group-item control loader">
            <div class="list-group-item">
                <h3 class="blank-slate-pf-main-action">Loading...</h3>
            </div>
            <div class="list-view-pf-main-info">
                <div class="spinner spinner-lg blank-slate-pf-icon"></div>
            </div>
        </div>

        <div class="list-group-item control loadmore">
            <div class="list-view-pf-main-info">&nbsp;</div>
            <div class="list-view-pf-actions form-group">
                <button class="btn btn-default">load more</button>
            </div>
        </div>
    </div>

    <div id="helio-instancelist" class="list-group list-view-pf list-view-pf-view loadable">
        <div class="list-group-item control loader">
            <div class="list-group-item">
                <h3 class="blank-slate-pf-main-action">Loading...</h3>
            </div>
            <div class="list-view-pf-main-info">
                <div class="spinner spinner-lg blank-slate-pf-icon"></div>
            </div>
        </div>

        <div class="list-group-item control loadmore">
            <div class="list-view-pf-main-info">&nbsp;</div>
            <div class="list-view-pf-actions form-group">
                <button class="btn btn-default">load more</button>
            </div>
        </div>
    </div>
</div>