<?php /** @var \Helio\Panel\Model\User $user */ ?>
<div class="container-fluid">
    <div>
        <h2>
            Impersonate
        </h2>
        <ul>
            <?php
            if (isset($users)) {
                /** @var \Helio\Panel\Model\User $u */
                foreach ($users as $u) {
                    if ($u->getId() !== $user->getId()) {
                        echo '<button class="btn btn-primary impersonate" data-userid="' . $u->getId() . '">' . $u->getEmail() . '</button> ';
                    }
                }
            }
            ?>
        </ul>
    </div>
    <div>
        <h2>Generate Eternal Token (BE CAREFUL WITH IT!)</h2>
        <button class="btn btn-primary generate-eternal-token" data-userid="<?php echo $user->getId(); ?>">
            Generate
        </button>
    </div>
    <div>
        <h2>Generate Job Token</h2>
        <form onsubmit="return false;"><input type="text" placeholder="Job Id" id="jobid" name="jobid"/></form>
        <button class="btn btn-primary generate-job-token">
            Generate
        </button>
    </div>
    <div>
        <h2>Generate Instance Token</h2>
        <form onsubmit="return false;"><input type="text" placeholder="Instance Id" id="instanceid" name="instanceid"/></form>
        <button class="btn btn-primary generate-instance-token">
            Generate
        </button>
    </div>
    <div id="helio-joblist" class="list-group list-view-pf list-view-pf-view loadable">
        <div class="list-group-item control loader">
            <div class="list-group-item">
                <h3 class="blank-slate-pf-main-action">Loading...</h3>
            </div>
            <div class="list-view-pf-main-info">
                <div class="spinner spinner-lg blank-slate-pf-icon"></div>
            </div>
        </div>

        <div class="list-group-item control loadmore">
            <div class="list-view-pf-main-info">&nbsp;</div>
            <div class="list-view-pf-actions form-group">
                <button class="btn btn-default">load more</button>
            </div>
        </div>
    </div>

    <div id="helio-instancelist" class="list-group list-view-pf list-view-pf-view loadable">
        <div class="list-group-item control loader">
            <div class="list-group-item">
                <h3 class="blank-slate-pf-main-action">Loading...</h3>
            </div>
            <div class="list-view-pf-main-info">
                <div class="spinner spinner-lg blank-slate-pf-icon"></div>
            </div>
        </div>

        <div class="list-group-item control loadmore">
            <div class="list-view-pf-main-info">&nbsp;</div>
            <div class="list-view-pf-actions form-group">
                <button class="btn btn-default">load more</button>
            </div>
        </div>
    </div>
</div>