<h2 class="display c--white a--center">Your Jobs and Apps</h2>
<div class="container-fluid">
    <p>
        Apps are carefully selected and prepared by us to bring you the best experience.<br/>
        You can create Jobs that allow you to run apps depending on their type.
    </p>
</div>
<div class="container-fluid">
    <div class="row toolbar-pf">
        <div class="col-sm-12">
            <form class="toolbar-pf-actions" onsubmit="return false;">
                <div class="form-group toolbar-pf-filter">
                    <label class="sr-only" for="filter">Name</label>
                    <div class="input-group">
                        <input type="text" class="form-control" id="filter" placeholder="Filter List..."
                               data-item-selector="#helio-joblist > div.job" data-text-selector=".list-group-item-header"
                               onkeyup="filterItemsByTextSearch(this)">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div id="helio-joblist" class="list-group list-view-pf list-view-pf-view loadable">
        <div class="list-group-item control">
            <div class="list-view-pf-main-info">&nbsp;</div>
            <div class="list-view-pf-actions form-group">
                <button class="btn btn-default wizard-pf-open wizard-pf-complete wizard-pf-addJob"
                        data-target="#addJob">
                    Add a Job
                </button>
            </div>
        </div>
        <div class="list-group-item control loader">
            <div class="list-group-item">
                <h3 class="blank-slate-pf-main-action">Loading...</h3>
            </div>
            <div class="list-view-pf-main-info">
                <div class="spinner spinner-lg blank-slate-pf-icon"></div>
            </div>
        </div>
        <div class="list-group-item control loadmore">
            <div class="list-view-pf-main-info">&nbsp;</div>
            <div class="list-view-pf-actions form-group">
                <button class="btn btn-default">load more</button>
            </div>
        </div>
    </div>
</div>