<?php /** @var \Helio\Panel\Model\Instance $instance */ ?>
<div class="col-lg-12">
    <h2>Instance working but no workloads running yet.</h2>
    <p>
        The last thing you'll need to do is activating the runner on this server.
        Try clicking "Start" in the action menu.
    </p>
    <?php \Helio\Panel\Utility\ViewUtility::includePartial('instanceMetricsPanel', ['instance' => $instance]); ?>
</div>