<?php /** @var \Helio\Panel\Model\Instance $instance */ ?>
<div class="col-lg-12">
    <h2>Instance working properly.</h2>
    <p>
        <?php

        if ($instance->getSnapshotConfig()) {
            $config = json_decode($instance->getSnapshotConfig(), true);
            if (array_key_exists('url', $config) && $config['url']) {
                $url = filter_var($config['url'], FILTER_SANITIZE_URL);
                echo '<iframe src="' . $url . '" width="100%" height="400px" frameborder="0"></iframe>';
            }
        }
        ?>
    </p>
</div>