<?php /** @var \Helio\Panel\Model\Instance $instance */ ?>
<div class="col-lg-12">
    <h2>
        Please provision your server with our provision script.
    </h2>
    <p class="text text--big">
        The Server has been created but didn't yet report for duty...<br/>
        To confirm the server, execute the following command, which will securely
        set up your server and then join our cluster (currently Docker Swarm).
        You'll find technical details on our <a href="https://github.com/helio/setup">Github page</a>
    </p><br/><br/>
    <?php \Helio\Panel\Helper\ViewHelper::includePartial('instanceAddScript', ['email' => $instance->getOwner()->getEmail(), 'token' => $instance->getToken()]); ?>
</div>