<?php
/** @var \Helio\Panel\Model\User $user */
/** @var \Helio\Panel\Model\Instance $instance */
?>
<div class="col-lg-12">
    <h2>
        Please provision your server with our provision script.
    </h2>
    <p class="text text--big">
        The Server has been created but didn't yet report for duty...<br />
        To confirm the server, execute the following command, which will securely
        set up your server and then join our cluster (currently Docker Swarm).
        You'll find technical details on our <a href="https://github.com/helio/setup">Github page</a>
    </p><br/><br/>
    <pre class="prettyprint">
curl -fsSL un.idling.host -o start-computing.sh
if shasum -a 1 -s -c <(echo '<?php echo \Helio\Panel\Utility\ServerUtility::get('SCRIPT_HASH'); ?> start-computing.sh'); then
    sh start-computing.sh -m <?php echo $user->getEmail() . ' -t ' . $instance->getToken(); ?><!-- -->
fi</pre>
</div>