<?php /* @var \Helio\Panel\Model\Job $job */ ?>
<div class="col-lg-12">
    <p>Docker Exec with id <strong><?php echo $job->getId() ?></strong> and config</p>
    <pre><?php echo $job->getConfig(); ?></pre>

    <?php
    if ($job->getExecutions()) {
        echo '<p>List of Executions associated with this job:</p>';
        echo '<ul>';
        /** @var \Helio\Panel\Model\Execution $execution */
        foreach ($job->getExecutions() as $execution) {
            echo '<li>';
            echo '<span>Execution with id ' . $execution->getId() . ' and Status <strong>' . \Helio\Panel\Execution\ExecutionStatus::getLabel($execution->getStatus()) . '</strong></span><br />';
            if ($execution->getStats()) {
                echo '<span>Execution Results:</span><br />';
                echo '<pre class="prettyprint">' . $execution->getStats() . '</pre>';
            }
            echo '<hr /></li>';
        }
        echo '</ul>';
    }
    ?>
</div>