<?php /** @var \Helio\Panel\Model\Job $job */ ?>
<div class="col-lg-12">
    <p>
        The API for this job is ready. You can create Gitlab Runners by POST/PUT to this URL:
    </p>
    <?php
    echo '<pre class="prettyprint">';
    echo  \Helio\Panel\Utility\ExecUtility::getExecUrl($job);
    echo '</pre>';
    ?>
    <hr/>
    <h2>Try me!</h2>
    <form class="try-job"
          data-demourl="<?php echo  \Helio\Panel\Utility\ExecUtility::getExecUrl($job); ?>">
        <div class="form-group">

            <label for="name">
                runner Name
            </label>
            <br/>
            <input type="text" name="name" size="50" id="name">
        </div>
        <div class="form-group">

            <label for="token">
                runner token
            </label>
            <br/>
            <input type="text" name="token" size="50" id="token" readonly value="<?php echo $job->getConfig('gitlabToken'); ?>">
        </div>
        <div class="form-group">

            <label for="tags">
                runner tags (comma separated)
            </label>
            <br/>
            <input type="text" name="tags" size="50" id="tags" readonly value="<?php echo $job->getConfig('gitlabTags'); ?>">
        </div>
        <div class="form-group">
            <label for="endpoint">
                Gitlab URL
            </label>
            <br/>
            <input type="text" name="endpoint" size="50" id="endpoint" readonly value="<?php echo $job->getConfig('gitlabEndpoint'); ?>">
        </div>
        <button type="submit" class="btn btn-primary">
            Submit
        </button>
    </form>
    <hr/>
    <p>
        Optionally, you can set the following parameters.
    </p>
    <pre class="prettyprint">
{
    'token': "&lt;your Gitlab token&gt;",
    'name': "&lt;your Runner's name&gt";
}
</pre>

    <p>
        If you want to delete a runner, just push a DELETE request to the above URL. There, the following parameter is
        required:
    </p>

    <pre class="prettyprint">
{
    'name': "&lt;your Runner's name&gt";
}
</pre>
</div>