<?php /** @var \Helio\Panel\Model\Job $job */ ?>
<div class="col-lg-12">
    <p>
        The API for this job is ready. You can run EnergyPlus Jobs by POST to this URL:
    </p>
    <?php
    echo '<pre class="prettyprint">';
    echo \Helio\Panel\Utility\ExecUtility::getExecUrl($job);
    echo '</pre>';
    ?>
    <hr/>
    <h2>Try me!</h2>
    <form class="try-job"
          data-demourl="<?php echo \Helio\Panel\Utility\ExecUtility::getExecUrl($job); ?>">
        <div class="form-group">

            <label for="epw">
                Where can we download the epw file for this job(if empty, we'll use an example one)?
            </label>
            <br/>
            <input type="text" name="epw" size="50" id="epw"
                   value="https://energyplus.net/weather-download/south_america_wmo_region_3/CHL//CHL_Concepcion.856820_IWEC/CHL_Concepcion.856820_IWEC.epw">
        </div>
        <div class="form-group">
            <label for="idf">URL to your IDF file</label>
            <input type="text" name="idf" id="idf" value="https://pastebin.com/raw/zj2SAV5Z">
        </div>
        <button type="submit" class="btn btn-primary">
            Submit
        </button>
    </form>
    <hr/>
    <p>
        You have to set the following
    </p>
    <pre class="prettyprint">
{
"run_id": "&lt;ID für Rechnungsreferenz etc.&gt;",
"epw": "&lt;URL&gt;",
"idf": "&lt;URL&gt;",
"report_url": "&lt;URL where to report the results&gt;"
}
</pre>

    <p>
        If you want to delete a runner, just push a DELETE request to the above URL.
    </p>
    <?php
    if (isset($files)) {
        echo '<p>Files associated to this job</p><ul>';
        foreach ($files as $file) {
            if (strpos($file, 'tar.gz') !== false) {
                echo '<li><a target="_blank" href="' . \Helio\Panel\Utility\ExecUtility::getExecUrl($job, 'download/' . $file) . '>' . $file . '</a></li>';
            }
        }
        echo '</ul>';
    }
    ?>
    <br/>
    <p>
        Developer Information:
    </p>
    <pre class="prettyprint">
<?php echo \Helio\Panel\Utility\ExecUtility::getExecUrl($job, 'work/getnextinqueue', null); ?>
    </pre>
</div>