<?php /** @var \Helio\Panel\Model\Job $job */ ?>

<div class="list-group-item job loadable"
     data-id="<?php echo $job->getId(); ?>"
     data-status="<?php echo $job->getStatus(); ?>"
>

    <div class="list-view-pf-additional-info loader">
        <span>
            loading details...
        </span>
    </div>
    <div class="list-group-item-header">
        <div class="list-view-pf-expand">
            <span class="fa fa-angle-right"></span>
        </div>
        <div class="list-view-pf-actions">
            <div class="dropdown pull-right dropdown-kebab-pf">
                <button class="btn btn-link dropdown-toggle" type="button" id="dropdownKebabRight9"
                        data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="true">
                    <span class="fa fa-ellipsis-v"></span>
                </button>
                <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownKebabRight9">
                    <li><a data-action="job/remove" data-method="delete">Delete Job</a></li>
                </ul>
            </div>
        </div>

        <div class="list-view-pf-main-info">
            <div class="list-view-pf-left">
                <span class="fa fa-<?php echo $job->getType(); ?> list-view-pf-icon-sm status-<?php echo $job->getStatus(); ?>"></span>
            </div>
            <div class="list-view-pf-body">
                <div class="list-view-pf-description">
                    <div class="list-group-item-heading">
                        <p>
                            <?php echo $job->getName() . (isset($admin) ? ' by ' . $job->getOwner()->getEmail() : ''); ?>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="list-group-item-container container-fluid hidden">
        <div class="close">
            <span class="pficon pficon-close"></span>
        </div>
        <div class="row">
            <?php
            $filename = __DIR__ . '/jobDetailType-' . $job->getType() . '.phtml';
            if (file_exists($filename)) {
                /** @noinspection PhpIncludeInspection */
                include $filename;
            }
            ?>
        </div>
    </div>
</div>