<?php /** @var \Helio\Panel\Model\Instance $instance */ ?>

<div class="list-group-item instance loadable"
     data-status="<?php echo $instance->getStatus(); ?>"
     data-id="<?php echo $instance->getId(); ?>"
     data-idname="instanceid"
>
    <div class="loader loader-absolute">
        <div class="spinner spinner-lg"></div>
    </div>

    <div class="list-group-item-header">
        <div class="list-view-pf-expand">
            <span class="fa fa-angle-right"></span>
        </div>
        <div class="list-view-pf-actions<?php echo isset($admin) ? ' hidden' : ''; ?>">
            <div class="dropdown pull-right dropdown-kebab-pf">
                <button class="btn btn-link dropdown-toggle" type="button" id="dropdownKebabRight9"
                        data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="true">
                    <span class="fa fa-ellipsis-v"></span>
                </button>
                <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownKebabRight9">
                    <li>
                        <?php
                        if ($instance->getStatus() > \Helio\Panel\Instance\InstanceStatus::RUNNING) {
                            echo '<a data-action="instance/stop">Stop all workloads</a>';
                        } else {
                            echo '<a data-action="instance/start">Start running workloads</a>';
                        }
                        ?>
                    </li>
                    <li><a data-action="instance/cleanup" data-method="delete">Cleanup</a></li>
                    <li><a data-action="instance/remove" data-method="delete">Remove</a></li>
                    <li><a data-action="instance/provisionlogs" data-method="get">Logs of Server</a></li>
                    <li><a data-action="instance/runnerlogs" data-method="get">Logs of Runners</a></li>
                    <li><a data-action="instance/metrics/snapshot/create" data-method="put">create new metrics
                            snapshot</a>
                    </li>
                    <li>
                        <a data-action="instance/togglefree">
                            <?php echo $instance->isAllowFreeComputing() ? 'Dis' : 'A' ?>llow free Computing
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="list-view-pf-main-info">
            <div class="list-view-pf-left">
                <span title="<?php echo $instance->getId() ?>"
                      class="<?php echo \Helio\Panel\Instance\InstanceType::getIcon($instance->getInstanceType()); ?> list-view-pf-icon-sm status-<?php echo $instance->getStatus(); ?>">
                </span>
            </div>
            <div class="list-view-pf-body">
                <div class="list-view-pf-description">
                    <div class="list-group-item-heading">
                        <?php echo $instance->getFqdn() ?: 'FQDN not set!';
                        echo isset($admin) ? ' by ' . $instance->getOwner()->getEmail() : ''; ?>
                    </div>
                    <div class="list-group-item-text">
                        <?php echo $instance->getToken() ? 'Token: ' . $instance->getToken() : ''; ?>
                    </div>
                </div>
                <?php
                if (isset($info)) {
                    \Helio\Panel\Helper\ViewHelper::includePartial('/instanceAdditionalInfo', ['info' => $info]);
                }
                ?>
            </div>
        </div>
    </div>

    <div class="list-group-item-container container-fluid hidden">
        <div class="close">
            <span class="pficon pficon-close"></span>
        </div>
        <div class="row">
            <?php \Helio\Panel\Helper\ViewHelper::includePartial('instanceDetailStatus-' . $instance->getStatus(), ['instance' => $instance]); ?>
        </div>
    </div>
</div>
