<nav class="navbar navbar-default navbar-pf">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand">
            <img class="navbar-brand-icon" src="/images/logo.svg" alt="">
        </a>
    </div>
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right navbar-iconic navbar-utility">

            <li class="dropdown">
                <button class="btn btn-link dropdown-toggle nav-item-iconic" id="dropdownMenu2" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="true">
                    <span title="Username" class="fa pficon-user"></span>
                    <span class="dropdown-title"><?php echo $user->getName() ?? ''; ?> <span class="caret"></span>
          </span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                    <li><a href="/panel/logout">Log Out</a></li>
                </ul>
            </li>
        </ul>

        <ul class="nav navbar-nav navbar-primary">
            <li class="<?php echo $sellActive ?? '' ?>">
                <a href="/panel/sell">
                    &nbsp;SELL
                </a>
            </li>
            <li class="<?php echo $buyActive ?? '' ?>">
                <a href="/panel/buy">
                    &nbsp;BUY
                </a>
            </li>
        </ul>
    </div>
</nav>