<section class="hero">
    <div class="hero__inner wrapper">
        <div class="hero__content">
            <h1 class="display" style="word-wrap: break-word;">
                Hi <?php
                /** @var \Helio\Panel\Model\User $user * */
                if ($user) {
                    echo htmlspecialchars($user->getName() ?? $user->getEmail());
                }
                ?></h1>
            <h2>Welcome to the Helio Panel</h2>
            <?php
            if (isset($message) && $message) {
                echo <<<EOL
    <div class="alert alert-success" role="alert">            
        <p class="text text--big">
            $message
        </p>
    </div>
EOL;
            }
            ?>
        </div>
    </div>
</section>
<?php
if (!$user->getName() || !$user->getRole()) {
    printf(<<<EOFORM
<section class="calc">
<div class="calc__wrapper">
<div class="calc__inner">
<h2 class="display c--white a--center">Please Complete your profile</h2>
<form class="form c--white" action="/panel" method="post">
<div class="form__row" style="width: 100%%; display: initial;"
<div class="form__cell" style="width: 100%%;">
<label class="small small--upper c--white" for="username">
Your Name
</label>
<div class="input">
<input type="text" class="input__input" placeholder="Your Name" id="username" name="username" value="%1\$s"/>
</div>
<span class="small">How are you called?</span>
<br />
<br />
<label class="small small--upper c--white" for="role">
Your Role
</label>
<div class="input">
<input type="text" class="input__input" placeholder="Your Role" name="role" id="role" value="%2\$s"/>
</div>
<span class="small">Please briefly describe your professional role<br />(e.g. "Developer", "CTO", "DevOps" or similar).</span>
</div>
<br />
<br />
<input type="submit" style="margin-top: 0;" value="Save values" class="button button--wide form__button">
</form>
</div>
</div>
</section>
EOFORM
        , $user->getName(), $user->getRole());
}
?>
<section class="calc">
    <div class="calc__wrapper">
        <div class="calc__inner" style="width: 1000px; max-width: 1000px;">
            <h2 class="display c--white a--center">Your Servers</h2>
            <ul class="form c--white">
                <form action="/panel" method="post">
                    <div class="form__row" style="width: 100%; display: initial;">
                        <div class="form__cell" style="width: 100%;">
                            <label class="small small--upper c--white" for="servername">
                                Add a new Server
                            </label>
                            <div class="input">
                                <input type="text" class="input__input" placeholder="Server Name" id="servername"
                                       name="servername" required/>
                            </div>
                        </div>
                        <input type="submit" style="margin-top: 0;" value="Add Server"
                               class="button button--wide form__button">
                    </div>
                </form>
                <br/>
                <div class="divider"></div>
                <br/>
                <?php
                if ($user && count($user->getServers()) > 0) {
                    foreach ($user->getServers() as $server) {
                        echo '<li>';
                        echo '<h3 class="c--white a--center">Server: ' . $server->getName() . '</h3>';
                        echo '<form action="/panel" method="post">';
                        echo '<label class="small small--upper c--white">';
                        echo '<br />Status: ' . ($server->getIp() ? 'verified from IP: ' : 'please verify with token: ');
                        if ($server->getFqdn()) {
                            echo '<br />Fqdn: ' . $server->getFqdn();
                        }
                        echo '</label >';
                        echo '<input type="text" class="input__input" value="' . ($server->getIp() ?: $server->getToken()) . '" readonly>';
                        if ($server->getIp()) {
                            if ($server->isRunning()) {
                                echo '<input type="hidden" name="stopserver" id="stopserver" value="' . $server->getId() . '"/>';
                                echo '<button type="submit" class="button button--reset">Stop all Workloads for ' . $server->getFqdn() . '</button>';
                            } else {
                                echo '<input type="hidden" name="startserver" id="startserver" value="' . $server->getId() . '"/>';
                                echo '<button type="submit" class="button button--reset">Start workloads for ' . $server->getFqdn() . '</button>';
                            }
                        }
                        echo '</form><br /></li><div class="divider"></div>';
                    }
                } else {
                    echo '<li>no Severs yet</li>';
                }
                ?>
            </ul>
        </div>
    </div>
</section>
<section class="calc">
    <div class="calc__wrapper">
        <div class="calc__inner" style="width: 1000px; max-width: 1000px;">
            <h2 class="display c--white a--center">Your Workloads</h2>
            <a style="border: 1px solid #000714;" class="button button--wide form__button"
               target="_blank" href="https://opencomputing.cloud/#apply">Request a Workload</a>
        </div>
    </div>
</section>

<section class="vision">
    <div class="vision__content">
        <h1 class="display">
            How to register your server
        </h1>
        <p class="text text--big">
            You can create a server in the list above which will generate a token for you.
            To validate the server, execute the following command. This will securely
            set up your server and then join our docker swarm.
        </p>
        <pre>
curl -fsSL un.idling.host -o start-computing.sh
if shasum -a 1 -s -c <(echo '<?php echo \Helio\Panel\Utility\ServerUtility::get('SCRIPT_HASH') ?> start-computing.sh'); then
    ./start-computing.sh
fi</pre>
    </div>
</section>