<h2 class="display c--white a--center">Your Servers</h2>
<ul class="form c--white">

    <?php

    /** @var \Helio\Panel\Model\User $user */
    if ($user && count($user->getServers()) > 0) {
        /** @var \Helio\Panel\Model\Server $server */
        foreach ($user->getServers() as $server) {
            echo '<li>';
            echo '<h3 class="c--white a--center">Server: ' . $server->getName() . '</h3>';
            echo '<form action="/panel/server/status" method="post">';
            echo '<label class="small small--upper c--white">';
            echo '<br />Status: ' . ($server->getIp() ? 'verified from IP: ' : 'please verify with token: ');
            if ($server->getFqdn()) {
                echo '<br />Fqdn: ' . $server->getFqdn();
            }
            echo '</label >';
            echo '<input type="text" class="input__input" value="' . ($server->getIp() ?: $server->getToken()) . '" readonly>';
            if ($server->getIp()) {
                if ($server->isRunning()) {
                    echo '<input type="hidden" name="stopserver" id="stopserver" value="' . $server->getId() . '"/>';
                    echo '<button type="submit" class="button button--reset">Stop all Workloads for ' . $server->getFqdn() . '</button>';
                } else {
                    echo '<input type="hidden" name="startserver" id="startserver" value="' . $server->getId() . '"/>';
                    echo '<button type="submit" class="button button--reset">Start workloads for ' . $server->getFqdn() . '</button>';
                }
            }
            echo '</form><br />';
            echo '<a href="/panel/server/logs?server=' . $server->getId() . '"> view logs for this server</a><br/>';
            echo '<a href="/panel/server/metrics?server=' . $server->getId() . '"> view metrics for this server</a><br/>';
            echo '</li><div class="divider"></div>';
        }
    } else {
        echo '<li>no Severs yet</li>';
    }
    ?>
</ul>